POST http://localhost:9000/app/signup
Content-Type: application/application/json
{
    "firstName": "ghanshyam",

    "middleName": "parag",

    "lastName": "patil",
    
    "email": "temp@gmail.com",
   
    "password": "temp@123"
}